### ISSUE TITLE
typos

### ISSUE THREAD

**Issue by xjzh123** [ZhiqiuCao/Googology#3]
公式(7.89)

```
∀x(∃o(o ∈ x∧¬∃n(n ∈ o))∨
 ∃a∃b∃c(a ∈ x∧b ∈ x∧c ∈ a∧c∈b∧¬(a=b))∨
 ∃c∀d(e ∈ x → ∃a(a ∈ e∧a ∈c∧∀b((b ∈ e∧b ∈ c) →a=b)))).
```

e是否应为d？

定理8.25

```
定理8.25 L 是语法可判定的，即存在某种算法，可以判定L中的命题是否为命题。
```

最后一个“命题”是否应该为“真命题”或“定理”？

**Comment by ZhiqiuCao** [comment]
关于公式(7.89)，此处确实有误，之后会进行修改。

关于定理8.25，这个命题实际上说明的是语法可判定性（\Gamma \vdash p），而非语义可判定性，因此并不涉及到命题的真假。
不过此处的表述确实有些问题，之后会改为“可以判定L中的命题是否可证”。
